"""SQL schema rewrite

Revision ID: c9d9fdd8cbe5
Revises: d2ad1de7bd95
Create Date: 2024-10-16 10:38:47.363945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9d9fdd8cbe5"
down_revision: Union[str, None] = "d2ad1de7bd95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("active_questionnaires", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "student_finished_at",
                sa.DateTime(timezone=True),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "teacher_finished_at",
                sa.DateTime(timezone=True),
                nullable=True,
            )
        )

    with op.batch_alter_table("question_templates", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_updated",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("template_id", sa.String(), nullable=False))
        batch_op.drop_constraint(
            "fk_questions_template_reference_id_question_templates",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_questions_template_id_question_templates"),
            "question_templates",
            ["template_id"],
            ["id"],
        )
        batch_op.drop_column("template_reference_id")
        batch_op.drop_column("custom_answer")
        batch_op.drop_column("selected_option")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("selected_option", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("custom_answer", sa.VARCHAR(), nullable=True))
        batch_op.add_column(
            sa.Column("template_reference_id", sa.VARCHAR(), nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_questions_template_id_question_templates"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_questions_template_reference_id_question_templates",
            "question_templates",
            ["template_reference_id"],
            ["id"],
        )
        batch_op.drop_column("template_id")

    with op.batch_alter_table("question_templates", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("last_updated")

    with op.batch_alter_table("active_questionnaires", schema=None) as batch_op:
        batch_op.drop_column("teacher_finished_at")
        batch_op.drop_column("student_finished_at")

    # ### end Alembic commands ###
