"""Add timezone support and server default to created_at in QuestionTemplate model

Revision ID: d2ad1de7bd95
Revises: 
Create Date: 2024-10-14 08:29:28.864258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2ad1de7bd95"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(table_name="question_templates") as batch_op:
        batch_op.alter_column(
            column_name="created_at",
            existing_type=sa.DATETIME(),
            type_=sa.DATETIME(timezone=True),
            server_default=sa.text(text="(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(table_name="question_templates") as batch_op:
        batch_op.alter_column(
            column_name="created_at",
            existing_type=sa.DATETIME(timezone=True),
            type_=sa.DATETIME(),
            server_default=None,
            existing_nullable=False,
        )
    # ### end Alembic commands ###
