// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251128095756_AddMockUserSeeding")]
    partial class AddMockUserSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Models.ActiveQuestionnaireResponseBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActiveQuestionnaireFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<int?>("OptionFK")
                        .HasColumnType("int");

                    b.Property<int>("QuestionFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OptionFK");

                    b.HasIndex("QuestionFK");

                    b.ToTable("ActiveQuestionnaireResponse");

                    b.HasDiscriminator().HasValue("ActiveQuestionnaireResponseBaseModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Database.Models.AnonymousActiveQuestionnaireModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.PrimitiveCollection<string>("CompletedParticipantIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("ParticipantIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestionnaireTemplateFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionnaireType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("ActiveQuestionnaire");

                    b.HasDiscriminator<int>("QuestionnaireType").HasValue(1);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Database.Models.AnonymousQuestionnaireResponseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActiveQuestionnaireFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActiveQuestionnaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("OptionFK")
                        .HasColumnType("int");

                    b.Property<int>("QuestionFK")
                        .HasColumnType("int");

                    b.Property<int>("ResponseCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiveQuestionnaireId");

                    b.HasIndex("OptionFK");

                    b.HasIndex("QuestionFK");

                    b.ToTable("AnonymousQuesionnaireResponse");
                });

            modelBuilder.Entity("Database.Models.ApplicationLogsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("Database.Models.QuestionnaireGroupModel", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupId");

                    b.HasIndex("TemplateId");

                    b.ToTable("QuestionnaireGroups");
                });

            modelBuilder.Entity("Database.Models.QuestionnaireOptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("OptionValue")
                        .HasColumnType("int");

                    b.Property<int>("QuestionFK")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionFK");

                    b.ToTable("QuestionnaireTemplateOption");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayText = "Viser lidt eller ingen forståelse for arbejdsopgaverne.",
                            OptionValue = 1,
                            QuestionFK = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            DisplayText = "Forstår arbejdsopgaverne, men kan ikke anvende den i praksis. Har svært ved at tilegne sig ny viden.",
                            OptionValue = 2,
                            QuestionFK = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayText = "Let ved at forstå arbejdsopgaverne og anvende den i praksis. Har let ved at tilegne sig ny viden.",
                            OptionValue = 3,
                            QuestionFK = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            DisplayText = "Mindre behov for oplæring end normalt. Kan selv finde/tilegne sig ny viden.",
                            OptionValue = 4,
                            QuestionFK = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            DisplayText = "Behøver næsten ingen oplæring. Kan ved selvstudium, endog ved svært tilgængeligt materiale, tilegne sig ny viden.",
                            OptionValue = 5,
                            QuestionFK = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            DisplayText = "Viser intet initiativ. Er passiv, uinteresseret og uselvstændig.",
                            OptionValue = 1,
                            QuestionFK = 2,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 7,
                            DisplayText = "Viser ringe initiativ. Kommer ikke selv med løsningsforslag. Viser ingen interesse i at tilrettelægge eget arbejde.",
                            OptionValue = 2,
                            QuestionFK = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            DisplayText = "Viser normalt initiativ. Kommer selv med løsningsforslag. Tilrettelægger eget arbejde.",
                            OptionValue = 3,
                            QuestionFK = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 9,
                            DisplayText = "Meget initiativrig. Kommer selv med løsningsforslag. Gode evner for at tilrettelægge eget og andres arbejde.",
                            OptionValue = 4,
                            QuestionFK = 2,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            DisplayText = "Overordentlig initiativrig. Løser selv problemerne. Tilrettelægger selvstændigt arbejdet for mig selv og andre.",
                            OptionValue = 5,
                            QuestionFK = 2,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 11,
                            DisplayText = "Uacceptabel",
                            OptionValue = 1,
                            QuestionFK = 3,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 12,
                            DisplayText = "Under middel",
                            OptionValue = 2,
                            QuestionFK = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 13,
                            DisplayText = "Middel",
                            OptionValue = 3,
                            QuestionFK = 3,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 14,
                            DisplayText = "Over middel",
                            OptionValue = 4,
                            QuestionFK = 3,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 15,
                            DisplayText = "Særdeles god",
                            OptionValue = 5,
                            QuestionFK = 3,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 16,
                            DisplayText = "Omgås materialer, maskiner og værktøj på en sløset og ligegyldig måde. Holder ikke sin arbejdsplads ordentlig.",
                            OptionValue = 1,
                            QuestionFK = 4,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 17,
                            DisplayText = "Bruger maskiner og værktøj uden megen omtanke. Mindre god orden og omhyggelighed.",
                            OptionValue = 2,
                            QuestionFK = 4,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 18,
                            DisplayText = "Påpasselighed og omhyggelighed middel. Rimelig god orden.",
                            OptionValue = 3,
                            QuestionFK = 4,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 19,
                            DisplayText = "Meget påpasselig både i praktik og teori. God orden.",
                            OptionValue = 4,
                            QuestionFK = 4,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 20,
                            DisplayText = "I høj grad påpasselig. God forståelse for materialevalg. Særdeles god orden.",
                            OptionValue = 5,
                            QuestionFK = 4,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 21,
                            DisplayText = "N/A",
                            OptionValue = 1,
                            QuestionFK = 5,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 22,
                            DisplayText = "N/A",
                            OptionValue = 1,
                            QuestionFK = 6,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 23,
                            DisplayText = "N/A",
                            OptionValue = 1,
                            QuestionFK = 7,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 24,
                            DisplayText = "Du møder ikke hver dag til tiden.",
                            OptionValue = 1,
                            QuestionFK = 8,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 25,
                            DisplayText = "Du møder næsten hver dag til tiden.",
                            OptionValue = 2,
                            QuestionFK = 8,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 26,
                            DisplayText = "Du møder hver dag til tiden.",
                            OptionValue = 3,
                            QuestionFK = 8,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 27,
                            DisplayText = "Du melder ikke afbud ved sygdom.",
                            OptionValue = 1,
                            QuestionFK = 9,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 28,
                            DisplayText = "Du melder, for det meste afbud, når du er syg.",
                            OptionValue = 2,
                            QuestionFK = 9,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 29,
                            DisplayText = "Du melder afbud, når du er syg.",
                            OptionValue = 3,
                            QuestionFK = 9,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 30,
                            DisplayText = "Du har et stort fravær.",
                            OptionValue = 1,
                            QuestionFK = 10,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 31,
                            DisplayText = "Du har noget fravær.",
                            OptionValue = 2,
                            QuestionFK = 10,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 32,
                            DisplayText = "Du har stort set ingen fravær.",
                            OptionValue = 3,
                            QuestionFK = 10,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 33,
                            DisplayText = "Du har ingen fravær.",
                            OptionValue = 4,
                            QuestionFK = 10,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 34,
                            DisplayText = "Du søger ingen praktikpladser.",
                            OptionValue = 1,
                            QuestionFK = 11,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 35,
                            DisplayText = "Du ved, at du skal søge alle relevante praktikpladser, men det kniber med handlingen.",
                            OptionValue = 2,
                            QuestionFK = 11,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 36,
                            DisplayText = "Du søger alle relevante praktikpladser, men skal have hjælp til at søge praktikpladser, der ligger længere væk end i din bopælskommune.",
                            OptionValue = 3,
                            QuestionFK = 11,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 37,
                            DisplayText = "Du søger alle relevante praktikpladser også dem der ligger uden for din bopælskommune.",
                            OptionValue = 4,
                            QuestionFK = 11,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 38,
                            DisplayText = "Du søger alle relevante praktikpladser også dem der ligger uden for din bopælskommune. Du søger også praktikplads inden for en anden uddannelse, som dit GF giver adgang til.",
                            OptionValue = 5,
                            QuestionFK = 11,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 39,
                            DisplayText = "Du har ikke en synlig profil på praktikpladsen.dk.",
                            OptionValue = 1,
                            QuestionFK = 12,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 40,
                            DisplayText = "Du skal ofte påmindes om at synliggøre din profil på praktikpladsen.dk.",
                            OptionValue = 2,
                            QuestionFK = 12,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 41,
                            DisplayText = "Du har altid en synlig, men ikke opdateret profil på praktikpladsen.dk.",
                            OptionValue = 3,
                            QuestionFK = 12,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 42,
                            DisplayText = "Du har altid en opdateret og synlig profil på praktikpladsen.dk.",
                            OptionValue = 4,
                            QuestionFK = 12,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Database.Models.QuestionnaireQuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowCustom")
                        .HasColumnType("bit");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("QuestionnaireTemplateFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireTemplateFK");

                    b.ToTable("QuestionnaireTemplateQuestion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowCustom = false,
                            Prompt = "Indlæringsevne",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            AllowCustom = false,
                            Prompt = "Kreativitet og selvstændighed",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            AllowCustom = false,
                            Prompt = "Arbejdsindsats",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            AllowCustom = false,
                            Prompt = "Orden og omhyggelighed",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            AllowCustom = false,
                            Prompt = "N/A",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            AllowCustom = false,
                            Prompt = "N/A",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            AllowCustom = false,
                            Prompt = "N/A",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 8,
                            AllowCustom = false,
                            Prompt = "Mødestabilitet",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 9,
                            AllowCustom = false,
                            Prompt = "Sygdom",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 10,
                            AllowCustom = false,
                            Prompt = "Fravær",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 11,
                            AllowCustom = false,
                            Prompt = "Praktikpladssøgning",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 12,
                            AllowCustom = false,
                            Prompt = "Synlighed",
                            QuestionnaireTemplateFK = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SortOrder = 11
                        });
                });

            modelBuilder.Entity("Database.Models.QuestionnaireTemplateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastUpated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("TemplateStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending(true, false);

                    b.HasIndex("Title", "Id")
                        .IsDescending(true, false);

                    b.ToTable("QuestionnaireTemplate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gennemførelsesprocedure for SKP-elever ved PRAKTIK NORD",
                            LastUpated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TemplateStatus = 0,
                            Title = "Evaluering af SKP-elever"
                        });
                });

            modelBuilder.Entity("Database.Models.TrackedRefreshTokenModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Token")
                        .IsRequired()
                        .HasColumnType("varbinary(900)");

                    b.Property<int?>("UserBaseModelId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserBaseModelId");

                    b.ToTable("TrackedRefreshToken");
                });

            modelBuilder.Entity("Database.Models.UserBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParticipantIds")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("ParticipantIds");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("UserBaseModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Database.Models.ActiveQuestionnaireStudentResponseModel", b =>
                {
                    b.HasBaseType("Database.Models.ActiveQuestionnaireResponseBaseModel");

                    b.HasIndex("ActiveQuestionnaireFK");

                    b.ToTable("ActiveQuestionnaireResponse");

                    b.HasDiscriminator().HasValue("ActiveQuestionnaireStudentResponseModel");
                });

            modelBuilder.Entity("Database.Models.ActiveQuestionnaireTeacherResponseModel", b =>
                {
                    b.HasBaseType("Database.Models.ActiveQuestionnaireResponseBaseModel");

                    b.HasIndex("ActiveQuestionnaireFK");

                    b.ToTable("ActiveQuestionnaireResponse");

                    b.HasDiscriminator().HasValue("ActiveQuestionnaireTeacherResponseModel");
                });

            modelBuilder.Entity("Database.Models.StandardActiveQuestionnaireModel", b =>
                {
                    b.HasBaseType("Database.Models.AnonymousActiveQuestionnaireModel");

                    b.Property<DateTime?>("StudentCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentFK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TeacherCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherFK")
                        .HasColumnType("int");

                    b.HasIndex("GroupId");

                    b.HasIndex("QuestionnaireTemplateFK");

                    b.HasIndex("StudentFK");

                    b.HasIndex("TeacherFK");

                    b.ToTable("ActiveQuestionnaire");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Database.Models.StudentModel", b =>
                {
                    b.HasBaseType("Database.Models.UserBaseModel");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("StudentModel");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            FullName = "Brigitte Cantrell",
                            Guid = new Guid("7f8669b1-82ef-4992-b129-98816c8062ae"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Brigitte.Cantrell"
                        },
                        new
                        {
                            Id = -2,
                            FullName = "Jenny Estes",
                            Guid = new Guid("b5f38c7a-2703-4f67-9952-5117fa4c5a9c"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Jenny.Estes"
                        },
                        new
                        {
                            Id = -3,
                            FullName = "Faulkner Vincent",
                            Guid = new Guid("99371161-f8c7-49ac-b4b1-5911e788eddf"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Faulkner.Vincent"
                        },
                        new
                        {
                            Id = -4,
                            FullName = "Dorothy Blake",
                            Guid = new Guid("064913db-078f-4838-88ff-32a8f952fc64"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Dorothy.Blake"
                        },
                        new
                        {
                            Id = -5,
                            FullName = "Matilda Hooper",
                            Guid = new Guid("9a074fd3-563d-45a9-92d2-d9536077222d"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Matilda.Hooper"
                        },
                        new
                        {
                            Id = -6,
                            FullName = "Fannie Bonner",
                            Guid = new Guid("282a6274-c871-4bf2-ae5c-87a54675ac5b"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Fannie.Bonner"
                        },
                        new
                        {
                            Id = -7,
                            FullName = "Flossie Francis",
                            Guid = new Guid("a6723d38-9a5c-4268-9d97-eb4ab767e0cd"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Flossie.Francis"
                        },
                        new
                        {
                            Id = -8,
                            FullName = "White Duffy",
                            Guid = new Guid("a93ba049-f2ab-4efd-8214-e3cb4c28c6a5"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "White.Duffy"
                        },
                        new
                        {
                            Id = -9,
                            FullName = "Mona Edwards",
                            Guid = new Guid("dab46273-b302-4aea-8f7c-00278a6c79a1"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Mona.Edwards"
                        },
                        new
                        {
                            Id = -10,
                            FullName = "Marcy Bowen",
                            Guid = new Guid("750d567f-7fb5-4797-8de6-1cce70bcee6a"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Marcy.Bowen"
                        },
                        new
                        {
                            Id = -11,
                            FullName = "Patti Hardin",
                            Guid = new Guid("8a477829-4131-4187-824b-0e1b1e86747a"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Patti.Hardin"
                        },
                        new
                        {
                            Id = -12,
                            FullName = "Carlson Lara",
                            Guid = new Guid("e34f1941-6bbd-4173-913f-db86d63981bc"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Carlson.Lara"
                        },
                        new
                        {
                            Id = -13,
                            FullName = "Lee Morris",
                            Guid = new Guid("2d50f55b-9065-4e64-b594-9c9f31c094a5"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Lee.Morris"
                        },
                        new
                        {
                            Id = -14,
                            FullName = "Sellers Tate",
                            Guid = new Guid("7949121f-188e-4541-9557-05004899fa82"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Sellers.Tate"
                        },
                        new
                        {
                            Id = -15,
                            FullName = "Fran Gordon",
                            Guid = new Guid("af6a88f1-c656-46a9-a001-77362ab47c58"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Fran.Gordon"
                        },
                        new
                        {
                            Id = -16,
                            FullName = "Prince Brady",
                            Guid = new Guid("772c0c62-b0e3-4804-904d-b9645d6d0889"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Prince.Brady"
                        },
                        new
                        {
                            Id = -17,
                            FullName = "Finch Hayes",
                            Guid = new Guid("32888c04-1fea-46cd-b767-59165f6bf74f"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Finch.Hayes"
                        },
                        new
                        {
                            Id = -18,
                            FullName = "Jannie Huber",
                            Guid = new Guid("c6df5ff6-ebe2-4f92-9771-94f0953f6745"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Jannie.Huber"
                        },
                        new
                        {
                            Id = -19,
                            FullName = "Munoz Warren",
                            Guid = new Guid("236d48e4-2b56-400c-83fe-824c469e22b0"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Munoz.Warren"
                        },
                        new
                        {
                            Id = -20,
                            FullName = "Consuelo Conrad",
                            Guid = new Guid("8ecc7d4f-6126-44bd-9c89-cb475d478bde"),
                            Permissions = 16,
                            PrimaryRole = "Student",
                            UserName = "Consuelo.Conrad"
                        });
                });

            modelBuilder.Entity("Database.Models.TeacherModel", b =>
                {
                    b.HasBaseType("Database.Models.UserBaseModel");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("TeacherModel");

                    b.HasData(
                        new
                        {
                            Id = -21,
                            FullName = "Goodman Powell",
                            Guid = new Guid("2fd332b4-39b0-4d4b-9e52-04cd9eea2dd4"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Goodman.Powell"
                        },
                        new
                        {
                            Id = -22,
                            FullName = "Howell Mcdonald",
                            Guid = new Guid("b3cefcee-3e40-43ed-bd7d-00e4e296cdb6"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Howell.Mcdonald"
                        },
                        new
                        {
                            Id = -23,
                            FullName = "Hansen Kemp",
                            Guid = new Guid("b6066162-a68e-4e15-841c-ce92c6c80e34"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Hansen.Kemp"
                        },
                        new
                        {
                            Id = -24,
                            FullName = "Brianna Ewing",
                            Guid = new Guid("9e7dc194-07f4-4f8f-b71a-e0f350b3c072"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Brianna.Ewing"
                        },
                        new
                        {
                            Id = -25,
                            FullName = "Nicholson Coffey",
                            Guid = new Guid("12e5a62e-865f-4c1c-94dd-e5cdaf47ae67"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Nicholson.Coffey"
                        },
                        new
                        {
                            Id = -26,
                            FullName = "Santiago Le",
                            Guid = new Guid("5c5a9a44-8fd8-43e3-9fb9-89842b441e34"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Santiago.Le"
                        },
                        new
                        {
                            Id = -27,
                            FullName = "Bentley Whitfield",
                            Guid = new Guid("7b39758b-109c-4128-af6f-b123dba45063"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Bentley.Whitfield"
                        },
                        new
                        {
                            Id = -28,
                            FullName = "Jamie Kirby",
                            Guid = new Guid("6662cd03-9ccf-4846-87eb-89dcc003ab9c"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Jamie.Kirby"
                        },
                        new
                        {
                            Id = -29,
                            FullName = "Stacie Woodard",
                            Guid = new Guid("1429127b-67d5-4259-8f27-5836475c2254"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Stacie.Woodard"
                        },
                        new
                        {
                            Id = -30,
                            FullName = "Cruz Gutierrez",
                            Guid = new Guid("41cdb0ce-8106-4dc8-8705-1bc4a8601c80"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Cruz.Gutierrez"
                        },
                        new
                        {
                            Id = -31,
                            FullName = "Lancaster Booker",
                            Guid = new Guid("351ab5d0-a12f-4951-9dd8-baddd4ab872b"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Lancaster.Booker"
                        },
                        new
                        {
                            Id = -32,
                            FullName = "Christie Pate",
                            Guid = new Guid("7eaaf007-b414-40ad-b172-04afc3f31d02"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Christie.Pate"
                        },
                        new
                        {
                            Id = -33,
                            FullName = "Powell Mccoy",
                            Guid = new Guid("7087977a-b3dc-4d31-80cc-8878197b9afe"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Powell.Mccoy"
                        },
                        new
                        {
                            Id = -34,
                            FullName = "Judith Chan",
                            Guid = new Guid("bb2cac58-50bf-4cc0-9c46-77754c548d4b"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Judith.Chan"
                        },
                        new
                        {
                            Id = -35,
                            FullName = "Knox Whitley",
                            Guid = new Guid("d354e86f-9604-451d-bfc7-267fe881a3a8"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Knox.Whitley"
                        },
                        new
                        {
                            Id = -36,
                            FullName = "Mills Taylor",
                            Guid = new Guid("4debbb11-51d3-4b1e-aeef-c671ecfd26d2"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Mills.Taylor"
                        },
                        new
                        {
                            Id = -37,
                            FullName = "Kirby Galloway",
                            Guid = new Guid("e8795a6b-dc79-4c7d-a869-7cfae232439d"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Kirby.Galloway"
                        },
                        new
                        {
                            Id = -38,
                            FullName = "Hardy Cook",
                            Guid = new Guid("088b71f2-a638-4f4e-83d3-08d12e0f520d"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Hardy.Cook"
                        },
                        new
                        {
                            Id = -39,
                            FullName = "Adeline Martin",
                            Guid = new Guid("c4fd7938-d6b4-4e5b-aa38-b446a5a27384"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Adeline.Martin"
                        },
                        new
                        {
                            Id = -40,
                            FullName = "Jackie Maddox",
                            Guid = new Guid("0a14fb34-00d9-4854-a0ae-dfbe3a8595aa"),
                            Permissions = 24,
                            PrimaryRole = "Teacher",
                            UserName = "Jackie.Maddox"
                        });
                });

            modelBuilder.Entity("Database.Models.ActiveQuestionnaireResponseBaseModel", b =>
                {
                    b.HasOne("Database.Models.QuestionnaireOptionModel", "Option")
                        .WithMany()
                        .HasForeignKey("OptionFK");

                    b.HasOne("Database.Models.QuestionnaireQuestionModel", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionFK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Database.Models.AnonymousQuestionnaireResponseModel", b =>
                {
                    b.HasOne("Database.Models.StandardActiveQuestionnaireModel", "ActiveQuestionnaire")
                        .WithMany("AnonymousQuestionnaireResponses")
                        .HasForeignKey("ActiveQuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.QuestionnaireOptionModel", "Option")
                        .WithMany()
                        .HasForeignKey("OptionFK");

                    b.HasOne("Database.Models.QuestionnaireQuestionModel", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionFK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ActiveQuestionnaire");

                    b.Navigation("Option");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Database.Models.QuestionnaireGroupModel", b =>
                {
                    b.HasOne("Database.Models.QuestionnaireTemplateModel", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Database.Models.QuestionnaireOptionModel", b =>
                {
                    b.HasOne("Database.Models.QuestionnaireQuestionModel", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Database.Models.QuestionnaireQuestionModel", b =>
                {
                    b.HasOne("Database.Models.QuestionnaireTemplateModel", "QuestionnaireTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionnaireTemplateFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionnaireTemplate");
                });

            modelBuilder.Entity("Database.Models.TrackedRefreshTokenModel", b =>
                {
                    b.HasOne("Database.Models.UserBaseModel", null)
                        .WithMany("TrackedRefreshTokens")
                        .HasForeignKey("UserBaseModelId");
                });

            modelBuilder.Entity("Database.Models.UserBaseModel", b =>
                {
                    b.HasOne("Database.Models.AnonymousActiveQuestionnaireModel", null)
                        .WithMany("Users")
                        .HasForeignKey("ParticipantIds");
                });

            modelBuilder.Entity("Database.Models.ActiveQuestionnaireStudentResponseModel", b =>
                {
                    b.HasOne("Database.Models.StandardActiveQuestionnaireModel", "ActiveQuestionnaire")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("ActiveQuestionnaireFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveQuestionnaire");
                });

            modelBuilder.Entity("Database.Models.ActiveQuestionnaireTeacherResponseModel", b =>
                {
                    b.HasOne("Database.Models.StandardActiveQuestionnaireModel", "ActiveQuestionnaire")
                        .WithMany("TeacherAnswers")
                        .HasForeignKey("ActiveQuestionnaireFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveQuestionnaire");
                });

            modelBuilder.Entity("Database.Models.StandardActiveQuestionnaireModel", b =>
                {
                    b.HasOne("Database.Models.QuestionnaireGroupModel", "Group")
                        .WithMany("Questionnaires")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.QuestionnaireTemplateModel", "QuestionnaireTemplate")
                        .WithMany("ActiveQuestionnaires")
                        .HasForeignKey("QuestionnaireTemplateFK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Database.Models.StudentModel", "Student")
                        .WithMany("ActiveQuestionnaires")
                        .HasForeignKey("StudentFK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Database.Models.TeacherModel", "Teacher")
                        .WithMany("ActiveQuestionnaires")
                        .HasForeignKey("TeacherFK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("QuestionnaireTemplate");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Database.Models.AnonymousActiveQuestionnaireModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Database.Models.QuestionnaireGroupModel", b =>
                {
                    b.Navigation("Questionnaires");
                });

            modelBuilder.Entity("Database.Models.QuestionnaireQuestionModel", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Database.Models.QuestionnaireTemplateModel", b =>
                {
                    b.Navigation("ActiveQuestionnaires");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Database.Models.UserBaseModel", b =>
                {
                    b.Navigation("TrackedRefreshTokens");
                });

            modelBuilder.Entity("Database.Models.StandardActiveQuestionnaireModel", b =>
                {
                    b.Navigation("AnonymousQuestionnaireResponses");

                    b.Navigation("StudentAnswers");

                    b.Navigation("TeacherAnswers");
                });

            modelBuilder.Entity("Database.Models.StudentModel", b =>
                {
                    b.Navigation("ActiveQuestionnaires");
                });

            modelBuilder.Entity("Database.Models.TeacherModel", b =>
                {
                    b.Navigation("ActiveQuestionnaires");
                });
#pragma warning restore 612, 618
        }
    }
}
